### ISSUE TITLE
project #01 - Alice in Chains Tribute Page [OK]

### ISSUE THREAD

**Issue by gughog** [gughog/freeCodeCamp-projects#1]
# To do

- [x] User Story #1: My tribute page should have an element with a corresponding id="main", which contains all other elements.

- [x] User Story #2: I should see an element with a corresponding id="title", which contains a string (i.e. text) that describes the subject of the tribute page (e.g. "Dr. Norman Borlaug").

- [x] User Story #3: I should see a div element with a corresponding id="img-div".

- [x] User Story #4: Within the img-div element, I should see an img element with a corresponding id="image".

- [x] User Story #5: Within the img-div element, I should see an element with a corresponding id="img-caption" that contains textual content describing the image shown in img-div.

- [x] User Story #6: I should see an element with a corresponding id="tribute-info", which contains textual content describing the subject of the tribute page.

- [x] User Story #7: I should see an a element with a corresponding id="tribute-link", which links to an outside site that contains additional information about the subject of the tribute page. HINT: You must give your element an attribute of target and set it to _blank in order for your link to open in a new tab (i.e. target="_blank").

- [x] User Story #8: The img element should responsively resize, relative to the width of its parent element, without exceeding its original size.

- [x] User Story #9: The img element should be centered within its parent element.
