### ISSUE TITLE
project #02 - A Survey Form [OK]

### ISSUE THREAD

**Issue by gughog** [gughog/freeCodeCamp-projects#2]
# ToDos:

- [x] User Story #1: I can see a title with id="title" in H1 sized text.

- [x] User Story #2: I can see a short explanation with id="description" in P sized text.

- [x] User Story #3: I can see a form with id="survey-form".

- [x] User Story #4: Inside the form element, I am required to enter my name in a field with id="name".

- [x] User Story #5: Inside the form element, I am required to enter an email in a field with id="email".

- [x] User Story #6: If I enter an email that is not formatted correctly, I will see an HTML5 validation error.

- [x] User Story #7: Inside the form, I can enter a number in a field with id="number".

- [x] User Story #8: If I enter non-numbers in the number input, I will see an HTML5 validation error.

- [x] User Story #9: If I enter numbers outside the range of the number input, which are defined by the min and max attributes, I will see an HTML5 validation error.

- [x] User Story #10: For the name, email, and number input fields inside the form I can see corresponding labels that describe the purpose of each field with the following ids: id="name-label", id="email-label", and id="number-label".

- [x] User Story #11: For the name, email, and number input fields, I can see placeholder text that gives me a description or instructions for each field.

- [x] User Story #12: Inside the form element, I can select an option from a dropdown that has a corresponding id="dropdown".

- [x] User Story #13: Inside the form element, I can select a field from one or more groups of radio buttons. Each group should be grouped using the name attribute.

- [x] User Story #14: Inside the form element, I can select several fields from a series of checkboxes, each of which must have a value attribute.

- [x] User Story #15: Inside the form element, I am presented with a textarea at the end for additional comments.

- [x] User Story #16: Inside the form element, I am presented with a button with id="submit" to submit all my inputs.
