### ISSUE TITLE
project #03 - A Product Landing page [OK]

### ISSUE THREAD

**Issue by gughog** [gughog/freeCodeCamp-projects#3]
# ToDos:

- [x] User Story #1: My product landing page should have a header element with a corresponding id="header".

- [x] User Story #2: I can see an image within the header element with a corresponding id="header-img". A company logo would make a good image here.

- [x] User Story #3: Within the #header element I can see a nav element with a corresponding id="nav-bar".

- [x] User Story #4: I can see at least three clickable elements inside the nav element, each with the class nav-link.

- [x] User Story #5: When I click a .nav-link button in the nav element, I am taken to the corresponding section of the landing page.

- [x] User Story #6: I can watch an embedded product video with id="video".

- [x] User Story #7: My landing page has a form element with a corresponding id="form".

- [x] User Story #8: Within the form, there is an input field with id="email" where I can enter an email address.

- [x] User Story #9: The #email input field should have placeholder text to let the user know what the field is for.

- [x] User Story #10: The #email input field uses HTML5 validation to confirm that the entered text is an email address.

- [x] User Story #11: Within the form, there is a submit input with a corresponding id="submit".

- [x] User Story #12: When I click the #submit element, the email is submitted to a static page (use this mock URL: https://www.freecodecamp.com/email-submit) that confirms the email address was entered and that it posted successfully.

- [x] User Story #13: The navbar should always be at the top of the viewport.

- [x] User Story #14: My product landing page should have at least one media query.

- [x] User Story #15: My product landing page should utilize CSS flexbox at least once.
