### ISSUE TITLE
project #05 - Build a Personal Portfolio Webpage

### ISSUE THREAD

**Issue by gughog** [gughog/freeCodeCamp-projects#5]
#ToDos:

- [x] 001: My portfolio should have a welcome section with an id of welcome-section.

- [x] 002: The welcome section should have an h1 element that contains text.

- [x] 003: My portfolio should have a projects section with an id of projects.

- [x] 004: The projects section should contain at least one element with a class of project-tile to hold a project.

- [x] 005: The projects section should contain at least one link to a project.

- [x] 006: My portfolio should have a navbar with an id of navbar.

- [x] 007: The navbar should contain at least one link that I can click on to navigate to different sections of the page.

- [x] 008: My portfolio should have a link with an id of profile-link, which opens my GitHub or FCC profile in a new tab.

- [x] 009: My portfolio should have at least one media query.

- [x] 0010: The height of the welcome section should be equal to the height of the viewport.

- [x] 0011: The navbar should always be at the top of the viewport.
